const actions = {
    SUBMIT_LOGIN: "SUBMIT_LOGIN",
    SUBMIT_LOGIN_SUCCESS: "SUBMIT_LOGIN_SUCCESS",
    SUBMIT_LOGIN_FAILURE: "SUBMIT_LOGIN_FAILURE",

    RESET_FORM_LOGIN: "RESET_FORM_LOGIN",
    RESET_SIGN_IN: "RESET_SIGN_IN",

    LOGOUT_SUBMIT:'LOGOUT_SUBMIT',
    LOGOUT_SUBMIT_LOADING:'LOGOUT_SUBMIT_LOADING',
    LOGIN_LOADING:'LOGIN_LOADING'
};

export default actions;
